# Generated by Django 5.1.3 on 2025-02-03 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sid', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
